# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: All Notes
author: Devon Brackbill
logo: logo.png
copyright: 2024

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: all-notes.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/devonbrackbill/all_notes  # Online location of your book
  path_to_book: all_notes  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Ensure you have a proper structure defined
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
  home_page_in_navbar: true
  baseurl: ""
  comments:
    hypothesis: false
    utterances: false
  extra_footer: |
    <script src="_static/js/custom.js"></script>

# Add this to your existing _config.yml
sphinx:
  extra_extensions:
    - sphinx_togglebutton
  config:
    html_theme_options:
      toc_title: ''
      expand_sections: true
      use_sidenotes: true
      show_toc_level: 2
      collapse_navigation: false
      navigation_depth: 3
      show_nav_level: 2
      use_download_button: true
      use_fullscreen_button: true
      navigation_with_keys: true
    html_js_files:
      - _static/js/custom.js
    html_css_files:
      - _static/css/custom.css